# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Marcos Barone'
description: 'Administrador de empresas&nbsp;&bull;&nbsp;Aprendiendo Data Analytics &amp; Data Science&nbsp;&bull;&nbsp;E-commerce enthusiast'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: ''

# Online profiles
#facebook: ''
#twitter: ''
linkedin: 'marcosbarone'
email: 'marcosbarone89@gmail.com'
instagram: 'marcosbarone89'
resume: 'https://drive.google.com/open?id=0B6AnROWP1XU-ZllFLVlWSDhnVEE'
#pinterest: ''
#youtube: ''
github: 'mbarone89'
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
