# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Marcos Barone'
description: '&bull;&nbsp;Administrador&nbsp;de&nbsp;empresas&ensp;&bull;&nbsp;Aprendiendo&nbsp;Data&nbsp;Analytics&nbsp;&amp;&nbsp;Data&nbsp;Science&ensp;&bull;&nbsp;E-commerce&nbsp;enthusiast.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.png'

# Online profiles
#facebook: ''
#twitter: ''
linkedin: 'marcosbarone'
email: 'marcosbarone89@gmail.com'
instagram: 'marcosbarone89'
resume: 'https://drive.google.com/open?id=0B6AnROWP1XU-ZllFLVlWSDhnVEE'
#pinterest: ''
#youtube: ''
github: 'mbarone89'
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#blog_url: ''
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
